/** Runtime declarations are sourced from the checked TypeScript authoring module. */
export {
	default,
	LYNX_RENDERER_ID,
	lynxBackgroundRenderer,
	lynxBackgroundRendererRegistry,
	lynxBlockBackgroundRenderer,
	lynxBlockBackgroundRendererRegistry,
	lynxMainThreadRenderer,
	lynxMainThreadRendererRegistry,
	lynxRenderer,
	lynxRendererRegistry,
	lynxRendererRules,
	lynxRenderers,
	lynxRspeedyBackgroundRenderers,
	lynxBlockRspeedyBackgroundRenderers,
	lynxRspeedyMainThreadRenderers,
	lynxRspeedyRenderers,
	renderers,
} from './config.js';
